#!/bin/bash

# Filename: start
# Author: CorQB
# Created: January 4, 2019
# Modified: January 5, 2019
#
# This script is used to start two functions, 1) a command which listens to
# an active log file and reports to 2) a bot which posts given strings from
# the logfile to a webhook. This script is meant to be used with the repository
# https://github.com/destruc7i0n/shulker to make bot startup easier to automate.

#Edit these values with your unique environment variables

exec &> logs/start.log
echo "Beginning Log"

MCSERVER="/opt/msm/servers/webbcraft"
RCONIP="localhost"
RCONPORT="8000"
SHULKERPATH="/opt/msm/discord/shulker"
PATHTOSTART="/opt/msm/bin"


# Node-via-Yarn Function
yarnstart() {   cd $SHULKERPATH
                yarn start
                }
                
# Listener Function
listenerstart() {   tail -F /$MCSERVER/logs/latest.log | grep --line-buffered ": <" | while read x ; do echo -ne $x | \
                    curl -X POST -d @- http://$RCONIP:$RCONPORT/minecraft/hook ; done
                    }
                    
# Call node.js

if pidof -x "dsbot" >/dev/null; then
    echo "Bot is already running. Everything is OK."
else
    echo "Calling node.js..."
    screen -d -m -S "dsbot" yarnstart
fi

# Verify node start

if pidof -x "dsbot" >/dev/null; then
echo "Bot started correctly."
else echo "Bot failed to start: check yarn.log for more information."
fi


# Start listener

if pidof -x "listener" >/dev/null; then
    echo "Listener is already running. Everything is OK."
else
    echo "Starting listener..."
    screen -d -m -S "listener" listenerstart
fi

# Verify listener start

if pidof -x "listener" >/dev/null; then
echo "Listener Started."
else echo "Error: Check listener.log for more information."
fi
