#!/bin/bash

# Filename: stop
# Author: CorQB
# Created: January 4, 2019
# Modified: January 4, 2019

# A simple script to STOP screen sessions started by START script. 
# Appends a stopping message to the START script's logfile.

exec &>> logs/start.log
echo "---------------------------STOPPING--------------------------------"
echo date
echo ""
echo "Halting Discord Bot."
echo "Issuing STOP command."

# pseudo - update with proper kill commands
# kill "listener"
# kill "dsbot"

echo "Done. Everything is OK."
