#!/bin/bash

# Filename: stop
# Author: CorQB
# Created: January 4, 2019
# Modified: January 4, 2019

# A simple script to STOP screen sessions started by START script. 
# Appends a stopping message to the START script's logfile.

exec &>> dsbot.log

echo "Halting Discord Bot."

# pseudo - update with proper kill commands
# kill "listener"
# kill "dsbot"

echo "Done. Everything is OK."
